services:
  matrixbot:
    build: .
    container_name: matrixbot
    volumes:
      - ./config:/app/config
      - ./store:/app/store
      - ./logs:/app/logs
      - ./.env:/app/.env
    # network_mode: "host"
    ports:
      - "23983:23983"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
